create table item
(
    id                      integer generated by default as identity,
    appreciation_percentage double,
    description             varchar(255),
    group_id                integer,
    group_name              varchar(255),
    primary key (id)
);


create table postal_code
(
    id          integer not null,
    prefix_code varchar(255),
    suffix_code varchar(255),
    primary key (id)
);


create table property
(
    id             bigint not null,
    price          double,
    typology       integer,
    postal_code_id integer,
    primary key (id)
);

alter table property
    add constraint fk_property_postal_code_id
        foreign key (postal_code_id)
            references postal_code;